---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: naija-statup-guide
  label: page
  create: all
  match: "**/*"
- type: directory
  path: naija-startup-guide/public
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: naija-startup-guide/2019/06/04/6-RELIABLE-DELIVERY-COMPANIES-FOR-SMALL-BUSINESSES-IN-NIGERIA-2019
  label: Blog
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
